// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr37SJu7EoJzLZitm_o_EzBvRXYg0v1yI',
    appId: '1:1038003398725:web:8f2897a9a63b4393b2db2c',
    messagingSenderId: '1038003398725',
    projectId: 'cf-gestor-18778',
    authDomain: 'cf-gestor-18778.firebaseapp.com',
    storageBucket: 'cf-gestor-18778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEIm5mmRUJuow7v0Ve14mwFrBisHsunw',
    appId: '1:1038003398725:android:ca4f57f1c548b91fb2db2c',
    messagingSenderId: '1038003398725',
    projectId: 'cf-gestor-18778',
    storageBucket: 'cf-gestor-18778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnJ5kCEz4LUJShsR7sBb-GwTa7dfBlMg',
    appId: '1:1038003398725:ios:699e0d931866c863b2db2c',
    messagingSenderId: '1038003398725',
    projectId: 'cf-gestor-18778',
    storageBucket: 'cf-gestor-18778.appspot.com',
    iosBundleId: 'com.example.entregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnJ5kCEz4LUJShsR7sBb-GwTa7dfBlMg',
    appId: '1:1038003398725:ios:bf8619c3edd02f73b2db2c',
    messagingSenderId: '1038003398725',
    projectId: 'cf-gestor-18778',
    storageBucket: 'cf-gestor-18778.appspot.com',
    iosBundleId: 'com.example.entregas.RunnerTests',
  );
}
